### ISSUE TITLE
貌似在maven中央仓库没有找到坐标的位置

### ISSUE THREAD

**Issue by yichengxian** [jd-opensource/sql-analysis#1]
如题，请问上传了maven仓库了吗？

**Comment by huht123** [comment]
没，我明天上传一下-------- 原始邮件 --------发件人： yichengxian ***@***.***>日期： 2024年4月17日周三 18:05收件人： jd-opensource/sql-analysis ***@***.***>抄送： Subscribed ***@***.***>主    题： [jd-opensource/sql-analysis] 貌似在maven中央仓库没有找到坐标的位置 (Issue #1)
如题，请问上传了maven仓库了吗？

**Comment by huht123** [comment]
已上传，可以看一下集成文档，我更新了一下发自我的荣耀手机-------- 原始邮件 --------发件人： yichengxian ***@***.***>日期： 2024年4月17日周三 18:05收件人： jd-opensource/sql-analysis ***@***.***>抄送： Subscribed ***@***.***>主    题： [jd-opensource/sql-analysis] 貌似在maven中央仓库没有找到坐标的位置 (Issue #1)
如题，请问上传了maven仓库了吗？
