### ISSUE TITLE
oracle分析:  java.sql.SQLSyntaxErrorException: ORA-00905: missing keyword

### ISSUE THREAD

**Issue by yichengxian** [jd-opensource/sql-analysis#2]
刚发布到中央仓库,经过测试oracle好像分析不了，当然我想应该是未被考虑，
报错:

     java.sql.SQLSyntaxErrorException: ORA-00905: missing keyword 
      t oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:450)
        at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:399)
        at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1059)

以下是日志打印，
   sql analysis result = null
   sql analysis score error {"resultList":[]},{"sqlId":"com.xx.xx.dao.WorkPlanSharingDao.getSharingViewPersonIds","sourceSql":"select share_user_id as \"id\" from workplan_share ws WHERE shareto_user_id\u003d\u002722343\u0027 and ws.workplan_right\u003e0"}

**Comment by huht123** [comment]
目前确实，没考虑oracle的兼容性

**Comment by huht123** [comment]
后续我们会考虑，但可能优先级不高，如果你们使用oracle场景比较多的话，欢迎共建哈
